/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appView;

/**
 *
 * @author jose.ricardo
 */
public class CadastroTela extends javax.swing.JFrame {

    /**
     * Creates new form CadastroTela
     */
    public CadastroTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNomeField = new javax.swing.JTextField();
        jEmailField = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonRealizarCadastro = new javax.swing.JButton();
        jButtonIrLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNomeField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jNomeField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jNomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jNomeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 550, 40));

        jEmailField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jEmailField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 550, 40));

        jPasswordField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 550, 30));

        jButtonRealizarCadastro.setBackground(new java.awt.Color(240, 240, 240));
        jButtonRealizarCadastro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonRealizarCadastro.setContentAreaFilled(false);
        jButtonRealizarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRealizarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 550, 40));

        jButtonIrLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonIrLogin.setContentAreaFilled(false);
        jButtonIrLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIrLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cadastroimg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailFieldActionPerformed

    private void jNomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeFieldActionPerformed

    private void jButtonRealizarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarCadastroActionPerformed
        
    }//GEN-LAST:event_jButtonRealizarCadastroActionPerformed

    private void jButtonIrLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrLoginActionPerformed
        LoginTela TelaLogin = new LoginTela();
        TelaLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonIrLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIrLogin;
    private javax.swing.JButton jButtonRealizarCadastro;
    private javax.swing.JTextField jEmailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jNomeField;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables
}
