/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appView;

/**
 *
 * @author jose.ricardo
 */
public class LoginTela extends javax.swing.JFrame {

    /**
     * Creates new form LoginTela
     */
    public LoginTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEmailField = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonRealizarLogin = new javax.swing.JButton();
        jButtonIrCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEmailField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jEmailField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 620, 50));

        jPasswordField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 620, 30));

        jButtonRealizarLogin.setBackground(new java.awt.Color(240, 240, 240));
        jButtonRealizarLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonRealizarLogin.setContentAreaFilled(false);
        jButtonRealizarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRealizarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 620, 50));

        jButtonIrCadastro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonIrCadastro.setContentAreaFilled(false);
        jButtonIrCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIrCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/loginimg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailFieldActionPerformed

    private void jButtonRealizarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarLoginActionPerformed

    }//GEN-LAST:event_jButtonRealizarLoginActionPerformed

    private void jButtonIrCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrCadastroActionPerformed
        LoginTela TelaLogin = new LoginTela();
        TelaLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonIrCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIrCadastro;
    private javax.swing.JButton jButtonRealizarLogin;
    private javax.swing.JTextField jEmailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables
}
